### ISSUE TITLE
sellLimit

### ISSUE THREAD

**Issue by Kraay89** [Durendal/bleuBot#3]
Your sellLimit function calls "self.makePrivateCallAPI" instead of the "self._makePrivateAPICall"
it throws an obvious error.

Also no "self._setParams(params)" is called. The API thus returns a {u'message': u'Invalid Market', u'result': [], u'success': u'false'}
#4

**Comment by Durendal** [comment]
Im sorry i didnt see this until your MR came in. I pushed a fix so all should be good. Also thanks for your contributions!
